### ISSUE TITLE
When running process is clicked, open the process

### ISSUE THREAD

**Issue by SrgjanX** [SrgjanX/SRX.ServiceMonitor#1]
<img width="399" alt="Screenshot_1" src="https://user-images.githubusercontent.com/11194119/154694569-2309bfc5-4558-4054-a44e-d99e60a779c5.png">

**Comment by sthamilton** [comment]
I have implemented a fix for this and put out a pull request if you're interested. Just now starting with trying to make some contributions and learning how it all works so I went ahead and worked on this before the issue was assigned to me.
